### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'net'

### ISSUE THREAD

**Issue by ChloeCarbonniere** [chenxin-dlut/TransT#152]
Hi !

While running run_video.py  with transt transt50, I have the following issue after selecting the ROI :

AttributeError: 'NoneType' object has no attribute 'net' in the net_wrappers.py file

Does anyone know how to solve this problem?

PS: As I am working on a  NVIDIA-SMI 565.75  , I had to upgrade to python=3.9 and cuda 12.6.
